/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilInput {
        /**
          * @default 'Enter the value'
         */
        "label": string;
        "max": number;
        "min": number;
        /**
          * @default 'number'
         */
        "type": 'text' | 'number';
        "value": string | number;
    }
}
declare global {
    interface HTMLStencilInputElement extends Components.StencilInput, HTMLStencilElement {
    }
    var HTMLStencilInputElement: {
        prototype: HTMLStencilInputElement;
        new (): HTMLStencilInputElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-input": HTMLStencilInputElement;
    }
}
declare namespace LocalJSX {
    interface StencilInput {
        /**
          * @default 'Enter the value'
         */
        "label"?: string;
        "max"?: number;
        "min"?: number;
        /**
          * @default 'number'
         */
        "type"?: 'text' | 'number';
        "value"?: string | number;
    }
    interface IntrinsicElements {
        "stencil-input": StencilInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-input": LocalJSX.StencilInput & JSXBase.HTMLAttributes<HTMLStencilInputElement>;
        }
    }
}
