/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilInput {
        /**
          * @default 'Enter the value'
         */
        "label": string;
        "max": number;
        "min": number;
        /**
          * @default 'number'
         */
        "type": 'text' | 'number';
        "value": string | number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilInputElement extends Components.StencilInput, HTMLStencilElement {
    }
    var HTMLStencilInputElement: {
        prototype: HTMLStencilInputElement;
        new (): HTMLStencilInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stencil-input": HTMLStencilInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilInput {
        /**
          * @default 'Enter the value'
         */
        "label"?: string;
        "max"?: number;
        "min"?: number;
        /**
          * @default 'number'
         */
        "type"?: 'text' | 'number';
        "value"?: string | number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stencil-input": StencilInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-input": LocalJSX.StencilInput & JSXBase.HTMLAttributes<HTMLStencilInputElement>;
        }
    }
}
